# theme: jekyll-theme-minimal
theme: jekyll-theme-architect
# theme: jekyll-theme-THEME-NAME # This line is already there. DO NOT delete it.
title: Sandybox005 # The main title of your website
description: > # A short description that appears right under the title
  Welcome! I'm a developer, designer, and student who loves building things.
  This is my personal page and portfolio.
